Ropey DVDs/Models/CastMember.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ropey_DVDs.Models
{
    public class CastMember
    {
       
        [ForeignKey("DVDTitle")]
        public Guid DVDNumber { get; set; }
        public DVDTitle? DVDTitle { get; set; }

        [ForeignKey("Actor")]
        public Guid ActorNumber { get; set; }
        public Actor? Actor { get; set; }
    }
}

Ropey DVDs/Controllers/CastMembersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ropey_DVDs.Data;
using Ropey_DVDs.Models;
using Ropey_DVDs.Models.ViewModels;

namespace Ropey_DVDs.Controllers
{
    public class CastMembersController : Controller
    {
        private readonly RopeyDBContext _context;

        public CastMembersController(RopeyDBContext context)
        {
            _context = context;
        }

        // GET: CastMembers
        public async Task<IActionResult> Index(string search)
        {

            if (search == null)
            {
                IList<DVDCastViewModel> viewModel = (from dt in _context.DVDTitles
                                                     join cm in _context.CastMembers
                                                     on dt.DVDNumber equals cm.DVDNumber
                                                     join a in _context.Actors
                                                     on cm.ActorNumber equals a.ActorNumber

                                                     select new DVDCastViewModel()
                                                     {
                                                         DVDTitle = dt.DVDNumber,
                                                         ActorSurname = a.ActorSurname

                                                     }).ToList();
                return View(viewModel);
            }

            else {
                IList<DVDCastViewModel> viewModel = (from dt in _context.DVDTitles
                                                     join cm in _context.CastMembers
                                                     on dt.DVDNumber equals cm.DVDNumber
                                                     join a in _context.Actors
                                                     on cm.ActorNumber equals a.ActorNumber
                                                     where a.ActorSurname == search
                                                     select new DVDCastViewModel()
                                                     {
                                                         DVDTitle = dt.DVDNumber,
                                                         ActorSurname = a.ActorSurname

                                                     }).ToList();
                return View(viewModel);

            }

            //DVDCastViewModel ropeyDBContext = new DVDCastViewModel();



            //foreach (var t in ropeyDBContext)
            //{
            //    Console.WriteLine("{0} {1}", t.DVDTitle, t.Actor);
            //}
           
        }


       

        // GET: CastMembers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var castMember = await _context.CastMembers
                .Include(c => c.Actor)
                .Include(c => c.DVDTitle)
                .FirstOrDefaultAsync(m => m.DVDNumber == id);
            if (castMember == null)
            {
                return NotFound();
            }

            return View(castMember);
        }

        // GET: CastMembers/Create
        public IActionResult Create()
        {
            ViewData["ActorNumber"] = new SelectList(_context.Actors, "ActorNumber", "ActorSurname");
            ViewData["DVDNumber"] = new SelectList(_context.DVDTitles, "DVDNumber", "DVDNumber");
            return View();
        }

        // POST: CastMembers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DVDNumber,ActorNumber")] CastMember castMember)
        {
            if (ModelState.IsValid)
            {
                //castMember.DVDNumber = Guid.NewGuid();
                _context.Add(castMember);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActorNumber"] = new SelectList(_context.Actors, "ActorNumber", "ActorSurname", castMember.ActorNumber);
            ViewData["DVDNumber"] = new SelectList(_context.DVDTitles, "DVDNumber", "DVDNumber", castMember.DVDNumber);
            return View(castMember);
        }

        // GET: CastMembers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var castMember = await _context.CastMembers.FindAsync(id);
            if (castMember == null)
            {
                return NotFound();
            }
            ViewData["ActorNumber"] = new SelectList(_context.Actors, "ActorNumber", "ActorSurname", castMember.ActorNumber);
            ViewData["DVDNumber"] = new SelectList(_context.DVDTitles, "DVDNumber", "DVDNumber", castMember.DVDNumber);
            return View(castMember);
        }

        // POST: CastMembers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("DVDNumber,ActorNumber")] CastMember castMember)
        {
            if (id != castMember.DVDNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(castMember);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CastMemberExists(castMember.DVDNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActorNumber"] = new SelectList(_context.Actors, "ActorNumber", "ActorSurname", castMember.ActorNumber);
            ViewData["DVDNumber"] = new SelectList(_context.DVDTitles, "DVDNumber", "DVDNumber", castMember.DVDNumber);
            return View(castMember);
        }

        // GET: CastMembers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var castMember = await _context.CastMembers
                .Include(c => c.Actor)
                .Include(c => c.DVDTitle)
                .FirstOrDefaultAsync(m => m.DVDNumber == id);
            if (castMember == null)
            {
                return NotFound();
            }

            return View(castMember);
        }

        // POST: CastMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var castMember = await _context.CastMembers.FindAsync(id);
            _context.CastMembers.Remove(castMember);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CastMemberExists(Guid id)
        {
            return _context.CastMembers.Any(e => e.DVDNumber == id);
        }
    }
}

Ropey DVDs/Views/CastMembers/Create.cshtml
@model Ropey_DVDs.Models.CastMember

@{
    ViewData["Title"] = "Create";
}


<h4>Create Cast Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DVDNumber" class="control-label"></label>
                <select asp-for="DVDNumber" class ="form-control" asp-items="ViewBag.DVDNumber"></select>
            </div>
            <div class="form-group">
                <label asp-for="ActorNumber" class="control-label"></label>
                <select asp-for="ActorNumber" class ="form-control" asp-items="ViewBag.ActorNumber"></select>
            </div>
            <div class="form-group mt-2" >
                <input type="submit" value="Create" class=" btn btn-outline-primary"/>
                <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
            </div>
        </form>
    </div>
</div>
@*
<div class="btn btn-primary" >
    <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ropey DVDs/Views/CastMembers/Delete.cshtml
@model Ropey_DVDs.Models.CastMember

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CastMember</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DVDTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DVDTitle.DVDNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actor.ActorSurname)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DVDNumber" />
        <input type="hidden" asp-for="ActorNumber" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
    </form>
</div>

Ropey DVDs/Views/CastMembers/Details.cshtml
@model Ropey_DVDs.Models.CastMember

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CastMember</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DVDTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DVDTitle.DVDNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actor.ActorSurname)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
   <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
</div>

Ropey DVDs/Views/CastMembers/Edit.cshtml
@model Ropey_DVDs.Models.CastMember

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CastMember</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DVDNumber" />
            <input type="hidden" asp-for="ActorNumber" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ropey DVDs/Views/CastMembers/Index.cshtml
@using Ropey_DVDs.Models.ViewModels
@model IList<DVDCastViewModel>


@{
    ViewData["Title"] = "Index";
}


<div style="font-family:Arial">

        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    

    @using(Html.BeginForm("Index","CastMembers",FormMethod.Get))
    {
 <form class="d-flex">
     <p>
         <input type="search" placeholder="Search Cast Member" value="search" style="width:300px;" />
         <input type="submit" value="Search" class="btn btn-primary" />
     </p>
    @Html.TextBox("search") <input type="submit" value="Search" style="width:150px"; class="btn btn-outline-info"  /><i class="fa-solid fa-magnifying-glass"></i> 
     </form>
    }

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-8">
            <h2 class="text-primary"> Cast Members </h2>

        </div>
        <div class="col-4 text-end">
            <a asp-action="Create" class="btn btn-outline-primary"> <i class="bi bi-plus-circle-fill"></i>
             
            </a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped" border="1">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.DVDTitle)*@
                DVD Title
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.ActorSurname)*@
               Actor Surname
            </th>
            
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DVDTitle)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.ActorSurname)
            </td>
        </tr>
}
    </tbody>
</table>

</div>